apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ai-shield-keys
  namespace: project-shield-userws
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: project-shield-vault
    kind: ClusterSecretStore
  target:
    name: ai-creds # This creates the local secret 'ai-creds'
    template:
      metadata:
        labels:
          # Tells Dev Spaces to grab this secret
          controller.devfile.io/mount-to-devworkspace: "true"
          controller.devfile.io/watch-secret: "true"
        annotations:
          # Injects as Environment Variables
          controller.devfile.io/mount-as: "env"
  data:
  - secretKey: ANTHROPIC_API_KEY
    remoteRef:
      key: ai-shield-master-creds
      property: ANTHROPIC_API_KEY