apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspace
metadata:
  name: ai-shield-alpha
  namespace: project-shield-userws
spec:
  routingClass: 'che'
  started: true
  template:
    # ⬇️ THIS IS THE MISSING PIECE ⬇️
    components:
      - name: che-code
        plugin:
          id: che-incubator/che-code/latest
    projects:
      - name: aicodershield
        git:
          remotes:
            origin: "https://github.com/jmaira-redhat/aicodersheild.git"