apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspace
metadata:
  name: ai-shield-alpha
  namespace: project-shield-userws
  annotations:
    # This tells the operator to inject the VS Code (Code-OSS) editor automatically
    che.eclipse.org/che-editor: che-incubator/che-code/latest
spec:
  routingClass: 'che'
  started: true
  template:
    projects:
      - name: aicodershield
        git:
          remotes:
            origin: "https://github.com/jmaira-redhat/aicodersheild.git"