apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspace
metadata:
  name: ai-shield-alpha
  namespace: project-shield-userws
spec:
  started: true 
  routingClass: 'che'
  template:
    projects:
      - name: aicodershield
        git:
          remotes:
            origin: "https://github.com/jmaira-redhat/aicodersheild.git"
    components:
      - name: dev-terminal
        container:
          image: quay.io/devspaces/ansible-creator-ee:latest
          memoryLimit: 2Gi
          mountSources: true